name: sales-dashboard
# services:

#   backend:
#     container_name: contenedor_backend
#     build:
#       context: ./backend/
#       dockerfile: Dockerfile.python.dev
#     restart: always
#     volumes:
#       - ./backend/:/code/usr/src/app/
#     # command: pipenv run uvicorn main:app --reload --host 0.0.0.0 --port 8000
#     command: pipenv run python manage.py runserver 0.0.0.0:8000
#     ports:
#       - "8000:8000"

  # frontend:
  #   container_name: contenedor_frontend
  #   build:
  #     context: ./frontend/
  #     dockerfile: Dockerfile.dev.javascript
  #   volumes:
  #     - ./frontend/:/code/usr/src/app/
  #   command: npm start
  #   ports:
  #     - "3000:3000"
  #   depends_on:
  #     - backend
# volumes:
#   volumen_postgres:
